### ISSUE TITLE
u dont gotta use jojoe77777\FormAPI\SimpleForm

### ISSUE THREAD

**Issue by T14Raptor** [Xenophilicy/XenoTransfer#3]

**Comment by Shelly7w7** [comment]
lol....

**Comment by Xenophilicy** [comment]
As you can see below, I use simpleForm to throw the UI to the player, please don't submit false issues.
```php
$form = new SimpleForm(function (Player $player, $data){
```

If you were to remove the directory from the code, you would encounter this error:
`Class 'XenoTransfer\SimpleForm' not found`
Therefore, it is needed for the stability of the UI.

Thanks
